reg=st_read("new_reg.gpkg")

via= raster("vias_teu_costo.sdat") %>% crop(reg) %>% mask(reg)
roam= raster("roam_costo.sdat") %>% crop(reg) %>% mask(reg)
polos= raster("polos_costo.sdat") %>% crop(reg) %>% mask(reg)
luces= raster("LUCES_costo.sdat") %>% crop(reg) %>% mask(reg)
cp= raster("cp_costo.sdat") %>% crop(reg) %>% mask(reg)
cobAg= raster("cobert_agric_costo.sdat") %>% crop(reg) %>% mask(reg)
atTuris= raster("atrac_turis_costo.sdat") %>% crop(reg) %>% mask(reg)
arCons= raster("Areas_conserv_costo.sdat") %>% crop(reg) %>% mask(reg)
anp= raster("ANP.sdat") %>% crop(reg) %>% mask(reg)
defo= raster("defo_ali_1.tif") %>% crop(reg) %>% mask(reg)
input= stack(via, roam, polos, luces, cp, cobAg, atTuris, arCons, anp, def)
roam= raster::resample(via,roam)
polos= raster::resample(via, polos)
luces= raster::resample(via,luces)
cp= raster::resample(via,cp)
cobAg= raster::resample(via,cobAg)
atTuris= raster::resample(via,atTuris)
arCons= raster::resample(via,arCons)
anp= raster::resample(via,anp)
defo= raster::resample(defo,via)
input= stack(via, roam, polos, luces, cp, cobAg, atTuris, arCons, anp, defo)
extend(defo)
raster::extent(defo)=raster::extent(via)


